// Generated by CodiumAI

describe('assertDefined_function', () => {
    const assertDefined = require('../cjs/defined');

    // Tests that assertDefined does not throw an error when a non-null element is passed
    it('test_happy_path_non_null', () => {
        expect(() => assertDefined('element')).not.toThrow();
    });

    // Tests that assertDefined does not throw an error when a non-undefined element is passed
    it('test_happy_path_non_undefined', () => {
        expect(() => assertDefined(123)).not.toThrow();
    });
    it('code_splitting', () => {
        expect(assertDefined).toBe(require('..').assertDefined);
    });
});
