// Generated by CodiumAI

import assertFinite = require('../cjs/finite');

describe('assertFinite', () => {
    // Asserts that a positive finite number is valid
    it('should validate a positive finite number', () => {
      expect(() => assertFinite(5)).not.toThrow();
    });

    // Asserts that a negative finite number is valid
    it('should validate a negative finite number', () => {
      expect(() => assertFinite(-5)).not.toThrow();
    });

    // Asserts that Infinity is not a valid number
    it('should throw an error when Infinity is passed', () => {
      expect(() => assertFinite(Infinity)).toThrow('must be finite');
    });

    // Asserts that -Infinity is not a valid number
    it('should throw an error when -Infinity is passed', () => {
      expect(() => assertFinite(-Infinity)).toThrow('must be finite');
    });
});
