name: assertion-lib CI/CD
on:
  push:
    branches:
      - main
    paths:
      - src/*.ts
  pull_request:
    branches:
      - main
    paths:
      - src/*.ts

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          always-auth: true
          registry-url: https://registry.npmjs.org
          token: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          always-auth: true
          registry-url: https://registry.npmjs.org
          token: ${{ secrets.NPM_AUTH_TOKEN }}
        
      - name: publish
        run: yarn publish --access=public
      
      
      