name: Pull Request check

on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  say-hi:
    continue-on-error: true
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check for existence of comment
        id: comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = "${{ github.event.pull_request.number }}";

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
            });

            return comments.some(comment => comment.body.includes('Hi, ${{ github.actor }}'));

      - name: Say hi
        uses: jungwinter/comment@v1
        if: steps.comment.outputs.result == 'false'
        with:
          type: create
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.pull_request.number }}
          body: |
            Hi, ${{ github.actor }}!
            Make sure to comply with the [Code of Conduct](https://github.com/${{ github.repository }}/blob/main/CODE_OF_CONDUCT.md), [security policy](https://github.com/${{ github.repository }}/blob/main/SECURITY.md) and [contribution guidelines](https://github.com/${{ github.repository }}/blob/main/CONTRIBUTING.md) before contributing to this repo.
  test:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn

      - name: Validate package.json
        run: yarn validate-package-json
      
      - name: Validate Markdown links
        run: yarn check-links

      - name: Run ESLint
        run: yarn lint
        
      - name: Build code
        run: yarn build
      
      - name: Run main test suites
        run: yarn test

      - name: Report build failed (if any)
        if: failure()
        uses: ./.github/workflows/pr-build-failed.yml
        with:
          pr-author: ${{ github.event.pull_request.user.login }}
          number: ${{ github.event.pull_request.number }}
  assign-and-ping:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: test
    if: success()
    steps:
      - name: Check CI status
        id: ci-check
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data } = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
            });
            const latestCheck = data.check_runs[0];
            return latestCheck.conclusion === 'success';

      - name: Assign pull request to yourself
        if: steps.ci-check.outputs.result == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const assignResponse = await github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              assignees: [context.repo.owner],
            });

      - name: Request code review
        if: steps.ci-check.outputs.result == 'true'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const requestReviewResponse = await github.pulls.createReviewRequest({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: [context.repo.owner],
            });
